### ISSUE TITLE
Default Value of the parameter do not change when moving from one version to another.

### ISSUE THREAD

**Issue by desaifly** [Microsoft/aspnet-api-versioning#300] opened 2018-05-21 18:22 UTC
**Description:**
When moving from one version to another the default value remains the same in the input box.

I am not sure where is the issue. I have reported this bug in the swagger-ui as well (#4577). 

**To reproduce:**

Go To 'Orders' and expand
Click on 'Try it out'
api-version parameter is '0.9' - It's correct
Select a spec 'V1'
go to Orders (The api-version parameter Default Value shown 1.0, which is correct)
Click on 'Try it out'
api-version parameter is '0.9' which is incorrect.

**Expected behavior**
api-version parameter need to be '1.0'

**Comment by commonsensesoftware** [comment] 2018-05-21 19:41
Is this for ASP.NET Core or Web API? The versions of Swagger are different and have ever so slightly different behaviors.

**Comment by desaifly** [comment] 2018-05-21 21:07
ASP.NET Core.

**Comment by commonsensesoftware** [comment] 2018-05-21 22:49
Hmm... I can't seem to repro your scenario. I went to the sample folder and ran:

`dotnet run`

Then I navigated to:

`http:/localhost:5000/swagger`

I subsequently followed your repro steps, but I see `1.0` properly popuated and the request URL generated by **Try it out!** was:

`http://localhost:5000/api/Orders/42?api-version=1.0`

**Comment by commonsensesoftware** [comment] 2018-06-06 20:52
Were you ever able to resolve this? I was able able to reproduce the behavior you are seeing. I wanted to make sure your issue is addressed before closing it out. Thanks.

**Comment by commonsensesoftware** [comment] 2018-06-13 15:53
I was unable to reproduce your scenario. The example I provide, and that was referenced, works without issue that I can recreate. If you still haven't addressed this, feel free to re-open this or create a new issue. A working repro that demonstrates the issue is always useful. The issue may be on the Swashbuckle side, which API versioning has no direct dependency or interaction. It's only used in examples for demonstration purposes. Thanks.

**Closed by commonsensesoftware** 2018-06-13 15:53 UTC
Labels: ASP.NET Core, answered, question
