### ISSUE TITLE
Web API Error : No route matches the supplied values : MVC ASP CORE 3.1.3

### ISSUE THREAD

**Issue by zachbester** [microsoft/aspnet-api-versioning#654] opened 2020-08-12 10:57 UTC
Hi All,

Have seen this issue in widespread and a lot of comments and suggestions to help correct it. But still not able to resolve this :(
Please see my implementation (URL assignment) using MVC ASP CORE 3.1.3. 

Tried both methods CreatedAtRoute and CreatedAtAction in the POST call but not having any luck. Logic for EF works
just fine but wanting to return resource info back on the response, I run into this exception.

Any help appreciated!

Nuget packages used..
![Nuget Packages](https://user-images.githubusercontent.com/52717481/90006739-c74c6100-dc99-11ea-8781-6d87284182f9.PNG)

ConfigureServices method..
![ConfigureServices](https://user-images.githubusercontent.com/52717481/90006881-0b3f6600-dc9a-11ea-9e61-699a81889351.PNG)

Controller class snippet..
![Controller](https://user-images.githubusercontent.com/52717481/90007058-53f71f00-dc9a-11ea-915f-2ee208d3f884.PNG)

GET method used..
![GET](https://user-images.githubusercontent.com/52717481/90007156-843ebd80-dc9a-11ea-8175-51a1ab54843d.PNG)

POST method used..
![POST](https://user-images.githubusercontent.com/52717481/90007375-ea2b4500-dc9a-11ea-91ec-93d92d63a24c.PNG)

**Comment by commonsensesoftware** [comment] 2020-08-12 14:34
This is because your versioning by URL segment and haven’t included it in **CreatedAtAction**. The API Version is _special_ and isn’t automatically included. Add the action parameter `ApiVersion version` to your action. Then add `version = version.ToString()` to the route parameters.

**Comment by bruno-brant** [comment] 2020-08-12 19:55
Hey, @commonsensesoftware, is this in the wiki? Otherwise, could we add it?

I've just spent a significant amount of time dealing with the same issue. I've tried many things that were close to passing a version to `routeValues`, but this one is tricky: for instance, I tried supplying both `apiVersion = "1"` and `version = new ApiVersion(...)`, which don't work.

**Comment by zachbester** [comment] 2020-08-13 06:31
Got this finally resolved now by doing the following....maybe helpful to someone else.

1. Within the Controller class, keep versioning and routing decoration as previously

![Controller Decoration](https://user-images.githubusercontent.com/52717481/90101175-80647700-dd3e-11ea-9bb9-2d2746ec4791.PNG)
 
2. Within the Controller class, replace method decorations [MapToApiVersion] with [Route("")], updated GET below..

![New GET](https://user-images.githubusercontent.com/52717481/90101317-c588a900-dd3e-11ea-8b25-9e7927dd697f.PNG)

3. Within the Controller class, added a Version property to the CreatedAtAction method within the POST action result method
    that matches the Controller ApiVersion decoration, updated POST below..

![New POST](https://user-images.githubusercontent.com/52717481/90101599-4d6eb300-dd3f-11ea-9fec-2efd1243843e.PNG)

Maybe not the most elegant workaround, but functional for now.

**Comment by bruno-brant** [comment] 2020-08-13 11:40
@zachbester, if it's any help I do have a repo with a solution that works a bit different than yours. 

https://github.com/bruno-brant/dotnet-api-versioning-error/tree/solution

You can also see a summary in the [readme](https://github.com/bruno-brant/dotnet-api-versioning-error/blob/master/README.md) or on [StackOverflow](https://stackoverflow.com/questions/63382832/createdataction-throws-invalidoperationexception-when-using-api-versioning).

**Comment by commonsensesoftware** [comment] 2020-08-14 17:29
@zachbester and @bruno-brant 

This scenario has been brought up a couple of times. Action parameters have a **BindingSource**. The **ApiVersion** is considered `BindingSource.Special` because it can come from multiple places. This behavior is similar to how the **CancellationToken** action parameter works. If memory serves me correctly, an action parameter must have `BindingSource.Path` to be considered in route URL generation, which makes sense.

The name of the action parameter that you add should not matter, but it _should_ match what you've defined in your route template to be sensical. The member you add that's passed to **CreatedAtAction** or **CreatedAtRoute** **must** be the same as that defined your route template. The routing system wants to serialize the **ApiVersion** type into the route parameter, which is incorrect. To address that, you simply call `.ToString()`. There _may_ be a way to solve that, but I haven't looked at it some time. It's certainly low on my list of things to spend time on.

Putting that all together, this will work every time:

```c#
[HttpGet]
[Route]
public ActionResult<DTODocumentCustomerRead> DocumentCustomerGet(int id) { /* ommited */ }

[HttpPost]
[Route]
public ActionResult<DTODocumentCustomerRead> DocumentCustomerCreate(
    DTODocumentCustomerCreate document,
    ApiVersion version)
{
    var model = _mapper.Map<DocumentCustomer>(document);

    _repository.DocumentCustomerCreate(model);
    _repository.SaveChanges();

     var dto = _mapper.Map<DTODocumentCustomerRead>(model);

    return CreatedAtAction(nameof(DocumentCustomerGet), new {id = dto.DocuID, version = version.ToString()}, dto);
}
```

The other way can get the requested API version is to call `HttpContext.GetRequestedApiVersion()`. This method _can_ return `null`, but in this context it will never be `null` by the time things have been routed to your action.

>_This is the way..._

I hope that helps.

**Comment by commonsensesoftware** [comment] 2020-09-17 23:05
Double-checking. Did this resolve your issue?

**Comment by bruno-brant** [comment] 2020-09-21 14:36
Hey @commonsensesoftware, it has. I'm sorry for forgetting to close the issue.

I do, however, insist that this should appear in the docs somehow (for instance, look at the comments from [my own answer](https://stackoverflow.com/a/63383951/227332) on SO). 

I might be able to help there if you want me to, by submitting a PR to the wiki.

**Comment by commonsensesoftware** [comment] 2020-09-21 21:24
@bruno-brant thanks for the confirmation. After considerable review of the ASP.NET Core codebase, I've come to the conclusion that this exactly the way things are expected to behave, even if developers don't expect it. The routing system **only** considers well-known route parameter tokens (ex: `[controller]`, `[action]`, etc) as an ambient value. An _ambient value_ is a route parameter that can come from route data without being explicitly specified in the values used to generate a route URL. I've made this argument before. You shouldn't expect something like `api/{tenant}/values` to work unless you specify the value `tenant` as an input. The API version route parameter is no different.

I'm sure people are grumbling at that. I get a **lot** of questions about this. On one hand, I'm inclined to leave it _as is_ because versioning this way is just _wrong_, but that would be a bad steward of the community. Despite my strong and experienced reservations, I've researched whether this can be intrinsically supported before conceding to just posting something in the FAQ. I can confirm that I have something that will work and solve this problem - for good. I'm tracking it as #663 for those that want to follow. I don't have a commitment as to the date it will be released, but it will appear in the next minor or patch release. In the interim, you can continue to specify the value explicitly.

I'll close this one out. Thanks.

**Closed by commonsensesoftware** 2020-09-21 21:24 UTC
Labels: answered, asp.net core, question
