### ISSUE TITLE
V2 and functions not working for API versioning using url path without attribute routing

### ISSUE THREAD

**Issue by saipraneeeth** [Microsoft/aspnet-api-versioning#371] opened 2018-10-16 05:14 UTC
Hey, 
I am trying to add versioning to our service. I am trying to create a sample project to play with. I want to have 2 versions of the Products API using URL path versioning (*api/v1/Products* and *api/v2/Products*) and without attribute routing. For that I plan to  have

- 2 controllers with same name in different folders (*Controllers/V1/ProductsController* and *Controllers/V2/ProductsController*)
- 2 models with same name in different folders ( *Models/V1/Product* and *Models/V2/Product*)
- Use custom *SelectController* to select the controller based on the version in url path
- Use *configuration.MapVersionedODataRoutes("ODataRoutes", "api/v{apiVersion}", models)* for all versioned OData routes

In the servive,the 2 controllers will call a base function, map the response they get in the form of base model, to their respective version models and return that versioned model response to the client. I am using **v3.0.0-beta1** version. I created a sample project with 2 controllers and 2 functions with the same name in different versions and am trying to implement the following GET api's

1) http://localhost:port/api/v1.0/Products/
2) http://localhost:port/api/v2.0/Products/
3) http://localhost:port/api/v1.0/Products/mypro
4) http://localhost:port/api/v2.0/Products/mypro

However only the first one is working. 
For the second one I am getting a 406 Not acceptable error as configuration is being considered only for v1 and not v2.
For the third and fourth one, I am getting a 404 error as functions are not being considered from the configuration. 

This is the detailed code.

**V1/ProductsController.cs**

```using System.Collections.Generic;
using System.Web.Http;
using Microsoft.AspNet.OData;
using ODataService.Models.V1;

namespace ODataService.Controllers.V1
{
    public class ProductsController : ODataController
    {
        private List<Product> products = new List<Product>()
        {
            new Product()
            {
                ID = 1,
                Name = "Bread",
                Category = "Food",
            },
            new Product()
            {
                ID = 2,
                Name = "Bread2",
                Category = "Food2",
            }
        };

        public List<Product> Get()
        {
            return products;
        }
        [HttpGet]
        public Product mypro()
        {
            return products[0];
        }
    }
}
```

**V2/ProductsController.cs**

```using System.Collections.Generic;
using System.Web.Http;
using Microsoft.AspNet.OData;
using ODataService.Models.V2;

namespace ODataService.Controllers.V2
{
    public class ProductsController : ODataController
    {
        private List<Product> products = new List<Product>()
        {
            new Product()
            {
                ID = 1,
                Name = "Bread",
                Item = "Pack"
            },
            new Product()
            {
                ID = 2,
                Name = "Bread2",
                Item = "Pack2"
            }
        };

        public List<Product> Get()
        {
            return products;
        }
        [HttpGet]
        public Product mypro()
        {
            return products[0];
        }
    }
}
```

**V1/Product.cs**

```namespace ODataService.Models.V1
{
    public class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
    }
}
```

**V2/Product.cs**
```namespace ODataService.Models.V2
{
    public class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Item { get; set; }
    }
}
```

**V1ModelConfiguration.cs**

```using Microsoft.AspNet.OData.Builder;
using Microsoft.Web.Http;

namespace ODataService.Configuration
{
   public class V1ModelConfiguration : IModelConfiguration
    {
        private static readonly ApiVersion V1 = new ApiVersion(1, 0);

        public void Apply(ODataModelBuilder builder, ApiVersion apiVersion)
        {
            if (apiVersion == V1)
            {
                builder.EntitySet<Models.V1.Product>("Products");
                builder.EntityType<Models.V1.Product>()
                    .Collection
                    .Function("mypro")
                    .ReturnsFromEntitySet<Models.V1.Product>("Product");
            }
        }
    }
}
```

**V2ModelConfiguration.cs**
```using Microsoft.AspNet.OData.Builder;
using Microsoft.Web.Http;

namespace ODataService.Configuration
{
    public class V2ModelConfiguration : IModelConfiguration
    {
        private static readonly ApiVersion V2 = new ApiVersion(2, 0);

        public void Apply(ODataModelBuilder builder, ApiVersion apiVersion)
        {
            if (apiVersion == V2)
            {
                builder.EntitySet<Models.V2.Product>("Products");
                builder.EntityType<Models.V2.Product>()
                    .Collection
                    .Function("mypro")
                    .ReturnsFromEntitySet<Models.V2.Product>("Product");
            }
        }
    }
}
```

**App_Start/WebApiConfig.cs**

```using System.Web.Http;
using System.Web.Http.Dispatcher;
using Microsoft.AspNet.OData.Builder;
using ODataService.Configuration;

namespace ODataService
{
    public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // Web API configuration and services

            // Web API routes
            config.MapHttpAttributeRoutes();
            config.AddApiVersioning();

            var modelBuilder = new VersionedODataModelBuilder(config)
            {
                ModelBuilderFactory = () => new ODataConventionModelBuilder(),
                ModelConfigurations =
                {
                    new V1ModelConfiguration(),
                    new V2ModelConfiguration()
                }
            };

            var models = modelBuilder.GetEdmModels();
            config.MapVersionedODataRoutes("ODataRoutes", "api/v{apiVersion}", models);

            var weveHttpControllerSelector = new MyHttpControllerSelector(config);

            config.Services.Replace(
                typeof(IHttpControllerSelector),
                weveHttpControllerSelector);
     }
  }
}
```

**MyHttpControllerSelector.cs**

```using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Controllers;
using System.Web.Http.Dispatcher;
using Microsoft.Web.Http.Versioning;
namespace ODataService
{


    public sealed class MyHttpControllerSelector : DefaultHttpControllerSelector
    {
        private readonly Lazy<Dictionary<string, HttpControllerDescriptor>> controllers;

        private readonly HttpConfiguration configuration;

        public MyHttpControllerSelector(HttpConfiguration configuration) : base(configuration)
        {
            this.configuration = configuration;
            this.controllers = new Lazy<Dictionary<string, HttpControllerDescriptor>>(this.InitializeControllerDictionary);
        }

        public override HttpControllerDescriptor SelectController(HttpRequestMessage request)
        {
            // Return default controller if no specific controller is found from controller mappers.
            return ControllerMappers.MapControllerDescriptor(this.controllers.Value, request) ?? base.SelectController(request);
        }

        private Dictionary<string, HttpControllerDescriptor> InitializeControllerDictionary()
        {
            var assembliesResolver = this.configuration.Services.GetAssembliesResolver();
            var controllersResolver = this.configuration.Services.GetHttpControllerTypeResolver();

            var controllerTypes = controllersResolver.GetControllerTypes(assembliesResolver);

           return controllerTypes.ToDictionary(
                type => type.FullName,
                type => new HttpControllerDescriptor(this.configuration, type.Name, type),
                StringComparer.OrdinalIgnoreCase);
        }
    }
}
```

**ControllerMappers.cs**
```using Microsoft.AspNet.OData.Routing;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Http.Controllers;
using System.Web.Http.Routing;

namespace ODataService
{
    public static class ControllerMappers
    {
        public static HttpControllerDescriptor MapControllerDescriptor(Dictionary<string, HttpControllerDescriptor> controllers, HttpRequestMessage request)
        {
            IHttpRouteData routeData = request.GetRouteData();

            // Find the correct controller from the initial dictionary by specific convention name.
            object controller;
            if (routeData.Values.TryGetValue(ODataRouteConstants.Controller, out controller))
            {

                HttpControllerDescriptor controllerDescriptor;

                object version;
                if (routeData.Values.TryGetValue("apiVersion", out version))
                {
                    version = Convert.ToInt64(Math.Floor(Convert.ToDouble(version))).ToString();
                    var versionController = ControllerMappers.MappingToVersionControllerName((string)version, (string)controller);
                
                    if (controllers.TryGetValue(versionController, out controllerDescriptor))
                    {
                        return controllerDescriptor;
                    }
                }
           }
            return null;
        }

        private static string MappingToVersionControllerName(string version, string controllerName)
        {
            return $"ODataService.Controllers.V{version}.{controllerName}Controller";
        }
    }
}
```

**Comment by commonsensesoftware** [comment] 2018-10-17 01:31
In short, you _broke_ things by change the **IHttpControllerSelector**. This is one of the intrinsic services that API versioning replaces when you call `AddApiVersioning`. Your **MyCustomControllerSelector** and **ControllerMappers** classes are unnecessary. If API versioning didn't provide this capability out-of-the-box, it would severely diminish it's value proposition.

I would consider looking at the [By Namespace example](../tree/master/samples/webapi/ByNamespaceWebApiSample).  Although that example is for plain old Web API, that's the layout that you're looking to achieve. You can use that layout for your controllers and the rest of the setup will be the same as the other OData examples.

Hopefully that gets you started. Let me know if you have more questions.

**Comment by saipraneeeth** [comment] 2018-10-17 04:46
I'm adding this to an existing service. This already has folder for each version inside a type, like *Controllers/V1, Controllers/V2, Models/V1, Models/V2* etc. Is there any way to do api versioning retaining this structure ?

**Comment by commonsensesoftware** [comment] 2018-10-17 16:51
Yes - of course. ;)

API versioning does **not** care about how you organize your code. You can put in one folder, one namespace, or many. Separating by folder and/or namespace is pretty common. The example link provided in my previous response shows this very setup.

That particular example also uses the latest 3.0 features to apply API version conventions by namespace; however, this can still be achieved with earlier versions' conventions albeit with a little bit of setup on your side. Either of these approaches would be the recommended setup since you indicated you don't want to use attributes.

**Comment by saipraneeeth** [comment] 2018-10-19 05:29
Thanks for the reply. I have removed **MyCustomControllerSelector**. The basic `GET` for v1 and v2 is working. But when I try to call the functions(*http://localhost:port/api/v1.0/Products/mypro
http://localhost:port/api/v2.0/Products/mypro*), I am getting a 404 error. 

I have only changed *App_Start/WebApiConfig* 

```using System.Web.Http.Dispatcher;
using Microsoft.AspNet.OData.Builder;
using Microsoft.Web.Http.Versioning.Conventions
using ODataService.Configuration;

namespace ODataService
{
    public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // Web API configuration and services

            // Web API routes
            config.AddApiVersioning(
                options =>
                {
                    options.ReportApiVersions = true;
                    options.Conventions.Add(new VersionByNamespaceConvention());
                });

            var modelBuilder = new VersionedODataModelBuilder(config)
            {
                ModelBuilderFactory = () => new ODataConventionModelBuilder(),
                ModelConfigurations =
                {
                    new V1ModelConfiguration(),
                    new V2ModelConfiguration()
                }
            };

            var models = modelBuilder.GetEdmModels();
            config.MapVersionedODataRoutes("ODataRoutes", "api/v{apiVersion}", models);
     }
  }
}
```

**Comment by commonsensesoftware** [comment] 2018-10-24 01:28
I looked things over again (from what I can see). It _looks_ like your setup of the function is incorrect.

Your setup is:
```c#
builder.EntityType<Models.V1.Product>()
       .Collection
       .Function("mypro")
       .ReturnsFromEntitySet<Models.V1.Product>("Product"); // BUG: 'Product' is not an entity set
```

When it should be:
```c#
builder.EntityType<Models.V1.Product>()
       .Collection
       .Function("mypro")
       .ReturnsFromEntitySet<Models.V1.Product>("Products");
```

Give that a whirl and see if things start working; otherwise, are you able to share your repro project? That would certainly save me all the time of copying your source here and setting up a new project to investigate.

**Comment by saipraneeeth** [comment] 2018-10-24 15:18
Tried with `Products`. Still it dint work. Guess `Product` is fine as the function returns a single entity not entitySet. Anyway this is the [link] (https://dev.azure.com/sasuggu/_git/ODataService-Test) to the repo.

**Comment by commonsensesoftware** [comment] 2018-11-18 22:53
The issue is that you expect to be able to use _unqualified_ action and functions, but your setup is incorrect to enable that.

First, add the following configuration method as you may have other options:

```c#
static void OnConfigureContainer(IContainerBuilder builder)
{
  builder.AddService(
    ServiceLifetime.Singleton,
    typeof(ODataUriResolver),
    sp => new UnqualifiedCallAndEnumPrefixFreeResolver() { EnableCaseInsensitive = true }
  );
}
```

Then simply pass this configuration method to **MapVersionedODataRoutes**:

```c#
config.MapVersionedODataRoutes("ODataRoutes", "api/v{apiVersion}", models, OnConfigureContainer);
```

The following routes now work as expected:
1. GET http://localhost:59239/api/v1.0/Products/
2. GET http://localhost:59239/api/v2.0/Products/
3. POST http://localhost:59239/api/v1.0/Products/mypro
4. GET http://localhost:59239/api/v2.0/Products/mypro

I hope that helps.

**Comment by commonsensesoftware** [comment] 2018-12-01 22:51
Were you able to get things working now?

**Comment by saipraneeeth** [comment] 2018-12-04 16:42
Sorry Chris. Dint get any notification about your comments. Just saw them.
Things are working now. Thanks for the help!!

**Comment by commonsensesoftware** [comment] 2018-12-04 18:46
Great! Just wanted to confirm before closing this out. Glad you got it working.

**Closed by commonsensesoftware** 2018-12-04 18:46 UTC
Labels: answered, asp.net web api, odata
