### ISSUE TITLE
Bug:Should clean the context.Items cache

### ISSUE THREAD

**Issue by mangshao** [Microsoft/aspnet-api-versioning#232] opened 2018-01-08 09:06 UTC
![](https://images2017.cnblogs.com/blog/411296/201711/411296-20171122234657040-1181612337.png)

**Comment by commonsensesoftware** [comment] 2018-01-10 16:24
The properties stored in `HttpContext.Items` is not a cache. They only store information about the current request. Per the [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?tabs=aspnetcore2x#working-with-httpcontextitems), the _"collection is available from the start of an HttpRequest and is discarded at the end of each request"_.

I'm not sure what the issue or expected action is here.

**Comment by mangshao** [comment] 2018-01-18 13:45
You can check this [blog](http://www.cnblogs.com/mangshao/p/7881237.html)

**Comment by commonsensesoftware** [comment] 2018-01-18 17:19
Unfortunately, I don't know what language that is nor what it says.

From what I can discern, it appears that you're encountering an issue with using the error page in conjunction with API versioning. Unfortunately, this is currently _by design_ and is a limitation in how _end of route_ middleware work. Both API versioning and the exception handler try to put themselves at the end of MVC pipeline. I've engaged with the ASP.NET team, but there needs to be some enhancements to the routing infrastructure in order to improve the experience.

I'm not entirely sure why a service would want an error page, but this is a topic that has come up a few times recently. I suggest taking a look at #221. I provided a workable solution that should help.

**Comment by commonsensesoftware** [comment] 2018-02-02 21:34
I was able to use a translator on your blog post. I suggest you follow the thread and guidance in #221. That will get you the desired result without changing the **IApiVersionRoutingPolicy**. This issue is not related to items in the HttpContext. I can provide lengthy explanation if you like.

**Comment by commonsensesoftware** [comment] 2018-07-31 14:28
Any further chance of this particular issue being a problem has been resolved by #280, which refactors to use a _feature_ instead. There's a reasonable chance this was also related, at least in part, to #306. These changes have been realized in the 3.0 release. Thanks for the feedback.

**Closed by commonsensesoftware** 2018-07-31 14:28 UTC
Labels: ASP.NET Core, answered, question
