### ISSUE TITLE
Question: Why is 2.0.0 not included with Microsoft.AspNetCore.All?

### ISSUE THREAD

**Issue by Jajunk** [Microsoft/aspnet-api-versioning#179] opened 2017-09-01 18:13 UTC
It seems like a strange thing that microsoft created this cool meta package to hold all of the AspNetCore references, except that it doesn't.

Will this package be added to the meta package at some point? And how will we know?

**Comment by commonsensesoftware** [comment] 2017-09-01 18:57
Fair question. You're not the first one to ask or make this statement. From the outside, I'm sure it just looks like "Microsoft". While it's true that I work for Microsoft, I'm an _army of one_ on this project and not part of the ASP.NET team. I started this project internally several years ago. It went through several iterations. With the new embrace of open source at Microsoft, I took on the task of making this project available to all. I personally felt it was important continue supporting Web API (which is where is all started) as well as support ASP.NET Core.

I can confirm that I have had conversations with the ASP.NET team and they are interested in making this project an intrinsic part of the platform.  I don't know exactly when that will happen. We've gone through a couple of cycles where the merger was bumped for other platform priorities. I do my best to stay on top of issues, bugs, and new releases to ensure there is general parity. That has probably promoted deferment on some level. I'm sure the merger will happen at some point. The next discussion will likely occur somewhere around the end of the calendar year.

I suspect that when things are merged into the platform, it will be widely advertised. Documentation will likely be added to MSDN and so on. I hope that helps clear things up.

**Comment by Jajunk** [comment] 2017-09-01 19:27
I see. Great answer thank you very much. Perhaps since I am not the first to ask about this, it should be included on the readme?  Thanks again for the quick response.

**Comment by commonsensesoftware** [comment] 2017-09-07 18:21
I think is issue is closed. I would think that most devs know that ASP.NET is hosted at https://github.com/aspnet (ASP.NET Core) and https://github.com/aspnetwebstack (ASP.NET Web API), but for clarity I'll consider updating the readme.  Thanks again.

**Closed by commonsensesoftware** 2017-09-07 18:21 UTC
Labels: answered, ASP.NET Core, question
