### ISSUE TITLE
Please add some diagnostics for easy troubleshooting

### ISSUE THREAD

**Issue by d-saravanan** [Microsoft/aspnet-api-versioning#224] opened 2017-12-14 07:15 UTC
We are having a tough time figuring out why 1 OData Function does not work fine and the rest works fine. We are getting the UnSupportedApiVersion error and could not be able to see that routes matched etc. Due to this, it is like we have to keep changing the names, the routes etc to make sure that these things work without any issue.

There can be something similar to the old system where we can enable <system.diagnostics> against the namespace and then we get the details of which steps passed and which ones failed etc. I made use of this feature when using the Microsoft.IdentityModel and other Authentication details. However, could not find any documents similar to that for this project. If possible, if it can be added with help-wanted tag, we will be able to contribute.

Kindly help us.

**Comment by commonsensesoftware** [comment] 2017-12-14 16:23
ASP.NET Web API provides a standard mechanism for tracing and logging a la the **ITraceWriter**. If an implementation has been registered in your configuration with:

```c#
configuration.Services.Replace( typeof( ITraceWriter ), new MyTraceWriter() );
```

or using your dependency injection framework of choice, API versioning will pick it up and leverage it.

I recommend this approach, even without API Versioning because Web API itself sends a lot of verbose logging information that can be useful during investigations. I can't speak to how much the OData extensions leverage this infrastructure; hopefully, they did the _right_ thing.

Currently, there isn't a tremendous amount of internal logging, but there definitely is _some_. If you still find the information being logged to be lacking, I'm willing to entertain improving the diagnostics story.

As an aside, you may be hitting a bug with OData functions. There is already an open issue. My examination thus far seems to indicate that there may be an issue resolving the function from the EDM - sometimes. I'm not sure that's your case, but you might want to check out the thread. I'm hoping to dig down into the details soon.

**Comment by d-saravanan** [comment] 2017-12-18 17:50
Thanks for the information. I am getting exception while resolving a normal get action call and a function too. I will try out the tracing Api and come up with the exact log details on OData action resolution. Also, I will try to read through the function resolution post. I will update you on the findings

**Comment by d-saravanan** [comment] 2017-12-18 18:01
Also, can you please point me to the particular class that I can plugin via the options and see what's happening while debugging through the code. Something like options.ActionSelector = new CustomActionSelector();. 

Please suggest me the right starting point

**Comment by commonsensesoftware** [comment] 2017-12-18 21:53
The **IHttpActionSelector** is a standard service in Web API. This is wired up in the `AddApiVersioning` extension method, which you can find in the [HttpConfigurationExtensions.cs](../blob/master/src/Microsoft.AspNet.WebApi.Versioning/System.Web.Http/HttpConfigurationExtensions.cs#L56).

The controller and action selection is largely in the main Web API versioning library. The OData variant is relatively small and deals with the particulars of OData like versioned EDMs.

I hope that helps.

**Comment by commonsensesoftware** [comment] 2017-12-29 01:06
Most of the tracing output in the Web API implementation is paired with the [HttpResponseExceptionFactory.cs](../blob/master/src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/HttpResponseExceptionFactory.cs) class. The content is largely on par with what Web API provides out-of-the-box. A few extra things like the requested API version and API version reporting are also included. This is really useful for clients, in particular, when API versions are malformed, missing, or are just not supported.

Any instrinic Web API components that required replacement retained their tracing functionality if they had any. I don't recall there being much. As long as you leverage **ITraceWriter**, you should be able to get some interesting details out of Web API. The story in ASP.NET Core is a bit better.

I think that should get you on your way. I happy to address specific gaps if I can. I should point out that there are likely gaps in the OData and/or Web API libraries. If something like OData isn't providing sufficent tracing information in Web API, it's better to file an issue in their [repo](../../../OData/WebApi/issues).

With respect to your original inquiry, I think you've hit a bug that I've now confirmed in #201. Have a fix in place and I'll be publishing as soon as I can. If you have something else specific to address on this thread, feel free to come back or reopen the issue.

**Closed by commonsensesoftware** 2017-12-29 01:06 UTC
Labels: ASP.NET Web API, OData (ASP.NET Web API), question
