### ISSUE TITLE
Using an unsupported method on a route incorrectly returns "UnsupportedApiVersion" response instead of a 404

### ISSUE THREAD

**Issue by nhambayi** [Microsoft/aspnet-api-versioning#219] opened 2017-12-07 18:11 UTC
Version 2.0.0

Example below uses url versioning but this occurs regardless of the versioning method used.

`
    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    public class TestController : Controller
    {
        [HttpGet]
        public string Get() => "Test Me!";
    }
`

A POST to the route "api/v1.0/test/" would result if the response 

`
{
    "Error": {
        "Code": "UnsupportedApiVersion",
        "Message": "The HTTP resource that matches the request URI 'http://hostname/api/v1.0/test/' does not support the API version '1.0'."
    }
}
`

While there should be an error response the error in this case is misleading because the route, if fact does not exist, and the error should in fact be "Not Found: 404"

**Comment by nhambayi** [comment] 2017-12-07 18:43
After looking at this I would say that the response code return "405 Method Not Allowed" is in fact CORRECT, but the message "UnsupportedApiVersion" is incorrect.

I have forked the code and I am investigating the issue.

**Comment by commonsensesoftware** [comment] 2017-12-07 18:52
Succinctly, I'll just say that this is _by design_. You may want to review the [error responses](../wiki/Error-Responses) wiki topic. If at least one route template matches the request, but not the API version you'll get 400 or 405 with the same error message. The message and meaning is the same. The difference between 400 and 405 is one indicates the service itself is not supported versus a specific action on the service is not supported. If the route does not exist at all, for any API version, you will get 404.

You might want to review the [error response provider](../wiki/Error-Response-Provider) wiki topic as well. It describes how you can change and influence the response. This will allow you to change the status code and/or message from 400/405 to 404.

I hope that helps.

**Comment by nhambayi** [comment] 2017-12-07 21:19
While I agree that, per the documentation, the behavior is as designed, I choose to disagree with the design. While the error code of 405 is correct, the error message does not reflect the reason for the 405 error. The method is not allowed in ANY version of the API and no change in the requested  API version will resolve the error.

This is a case where versioning is overriding the default aspnet core behavior of returning a 404 (though I agree that 405 is probably a better response code).

**Comment by commonsensesoftware** [comment] 2017-12-07 21:49
This is a consequence of versioning by URL segment. Personally, I'm not fan, but it's very common so it's supported. The URL is the _identifier_ and should not vary with new API versions. It's very similar to media type negotiation. Regardless of preference, it's important for all variations to have consistent behavior.

405 isn't even officially supported by ASP.NET Core yet so it has been a challenge supporting that. There are similar challenges with returning 404 when a route constraint is violated. ASP.NET Core doesn't provide any information as to why things didn't match. For example, it's not obvious to a client that  `api/v1/test/1` used a string for the id and `api/v2/test/2` uses an integer. If a client sends `api/v2/test/abc`, an argument can be made that the response can be 404 because the id will never exist or 400 because the id is invalid.  I've had a few chats with the ASP.NET team to help improve this in the future, but for now there aren't really any alternatives. If such a capability existed, API versioning could make saner decisions about the default response behavior and provide better extension points for you to control the way you want the results.

For now, my suggestion would be to change the error response provider to produce the status code that you want. Alternatively, you can use a versioning scheme that doesn't surface this problem such as by query string or media type.

If you want full control over the versioning policy, you can extend and replace the registered [Default API Versioning Policy](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/DefaultApiVersionRoutePolicy.cs). There isn't anything on the wiki about this because it's **way** down in the details and typically not something someone wants to change. However, should you want full control over how the policy is evaluated, this is the component that facilitates it. The default implementation should be straight forward, but if you have questions, I'm happy to answer them.

**Comment by commonsensesoftware** [comment] 2017-12-27 03:56
Though we may disagreed philosophically on the behavior, I'm not sure there is a universal answer for all. The goal was to hit the 80% and ensure there are plenty of hooks and extension points for the other 20%. Based on my suggestions, were you able to come up with a solution that was acceptable to you?

**Comment by nhambayi** [comment] 2017-12-27 05:42
I found your response acceptable. As long as the behavior is understood it's not a big issue. We have to document this so that it doesn't throw off our API users like it did me (for several hours sadly). Just thought od this. Would an option to override the default behavior be acceptable? People (and I mean me) tend not to read the documentation.  I would be will so create a pull request.

**Comment by commonsensesoftware** [comment] 2017-12-27 22:14
Honestly, there's even more to the story. #105 has been open for a long time to reflect other gaps such as the behavior with route constraints. Today, ASP.NET (Web API or Core) doesn't provide any useful extension points to decide what should happen when route conditions aren't met. To make an effective decision, we really need to know why a route was not matched (e.g. no match, constraints failed, etc). Then we need a way to override the default decision (e.g. 404 and so on). I've had a few chats with the ASP.NET team on this subject. They are thinking about it, but it hasn't made it to the committed feature list yet.

I've provided a few hooks (as presented above). Are you asking for something more or different, or are you just asking for better documentation?

I guess I didn't really elaborate on the justification for the behavior in _this_ thread. In the early days before GitHub, there was quite a bit of confusion about receiving 404 for an unsupported API version. 404 implies a temporary state by which a resource _may_ be available at some point. In the case of an unsupported API version, the decision tends to be permanent. You could argue for 410, but this implies that the resource _may_ have been available at one time, but that's not necessary true. Furthermore, the API version should be thought of as a parameter to resource representation instead of identity. If you accept that line of thinking, then you can see how an unmatched API version can yield 400/405/406 instead of 404. For example, `api/orders/1?api-version=1.0` and `api/orders/1?api-version=2.0` both refer to the same logical order resource, but their representations may be different. If API version 3.0 does not exist, then returning 404 for `api/orders/1?api-version=3.0` seems odd to me. The order _does_ exist, but cannot be represented in the API version 3.0 format. In this way, the request is _bad_ or unsupported.

I doubt I've changed your mind, but hopefully that provides some quantifying rationale. While most don't really care about response codes and bodies, there are a few of us who do. To that end, I definitely support providing the clearest and sanest alignment to the expected behavior as possible. I'm open to whatever suggestions you may have.

**Comment by commonsensesoftware** [comment] 2017-12-29 01:11
Thanks for all your input on this issue. These are always healthy discussions.  If you have some specific action you'd like to take, feel free to reply again or reopen the issue. For now, I think we've reached a conclusion. Know that there isn't a _magic_ answer that will make everyone happy, but I definitely try to keep things as aligned to the REST constraints as possible. Any place there is a gray area, I've tried to make sure there hooks and customizations to make things work the way _you_ want and not the way _I_ say. ;)

**Closed by commonsensesoftware** 2017-12-29 01:11 UTC
Labels: answered, ASP.NET Core, question
