### ISSUE TITLE
Content-type header value takes precedence over the Accept header value when looking for the version

### ISSUE THREAD

**Issue by gareth-horstmann** [Microsoft/aspnet-api-versioning#153] opened 2017-06-28 20:11 UTC
The MediaTypeApiVersionReader is looking at the _content-type_ header value before the _accept_ header value. The issue though is that when both are supplied (for example, when posting an image to the API, the content type is generally autopopulated to mutipart/form-data), but the _accept_ header has the version, the version doesn't get picked up as the _content-type_ check exits out of the Read method if its provided and an **"ApiVersionUnspecified"** error is returned.

Although the _content-type_ is a valid header to add the version value to, the _accept_ header should be the main header to use for versioning (not an expert but from what I've read on versioning a RESTful endpoint using content negotiation). So it should either check the _accept_ header value first and return if its provided OR check both header values and find the version in either.

**Comment by commonsensesoftware** [comment] 2017-06-28 22:46
This is by design, but let's explore _why_. First, the content type when posting an image or any other file will **not** be `multipart/form-data`. That is the MIME that gets used when you POST a file with a HTML form. This should only be the case if you have a web page (e.g. UI). This is not the case for an API.

Let's say that your REST API allows you to provide a thumbnail image for a customer. The API request would look something like:

```http
POST /customers/123/thumbnail HTTP/1.1
host: localhost
content-type: image/png; v=1.0
content-length: 2096

<Base64-encoded image content>
```

Arguably you don't even need the subsegment `/thumbnail` because you could infer that through media type negotiation. If a client posts an image for a customer, it must be for the thumbnail. For clarity, let's assume this segment exists. You might also choose that option, if different types of customer images are supported.

The reason that **Content-Type** is preferred over **Accept** is because **Content-Type** is unambiguous.  **Content-Type** is _required_ in order to make the request. It can also only be specified once. Any time that content is provided in the request, this is the optimal header to use for API versioning by media type. These rules only apply when the client provided content in a request; typically, for `POST`, `PUT`, and `PATCH`.

**Accept**, on the other hand, refers to the response format. This header can contain multiple, weighted media types. **Accept** is useful in a scenario where no content is specified in the request; typically, for `GET`, `DELETE`, `HEAD`, `OPTIONS`, etc. Since you can specify multiple media types, resolving the intended API version is more complex and ambiguous this way.

Imagine the following client request:

```http
GET /customers/123 HTTP/1.1
host: localhost
accept: application/json; q=0.8; v=1.0, application/json; q=0.2; v=2.0
```

The client is saying they prefer 1.0 weighted by 80%, but if you only have 2.0, they can accept that too. That may seem weird, but if you really want to get into API versioning with media types, then this is a _real_ scenario.

Ideally, it'd be nice if things can be implemented with a single HTTP header, but I haven't figured out a way to do that - yet. Similarly, crafting a request where the input and output API versions are not the same is not supported.

Consider:

```http
PATCH /customers/123 HTTP/1.1
host: localhost
accept: application/json; v=2.0
content-type: application/json; v=1.0
content-length: 20

{"firstName":"bob"}
```

This is the client saying they are sending you the 1.0 version of the customer in JSON, but they want the 2.0 version of the customer in JSON in the response. While this is technically supported in REST, that is not something supported out-of-the-box by this library. In fact, to make sure that never happens, **Content-Type** is detected and preferred over **Accept**.

I hope that helps clear things. I'm happy to discuss other options or ways to improve the implementation for folks that want to version their APIs this way.

**Comment by gareth-horstmann** [comment] 2017-06-29 06:45
Firstly, I just want to say that finding this framework was great and it was also good to see that it supports multiple API versioning techniques with all the chatter in each of the camps (trawling through all of the information online about URL, custom header, media type versioning has been quite time consuming). I was also pleasantly surprised to see that it also had the media type version supported (which I decided to use due to some of the arguments against URL versioning).

Ok, so I appreciate the fact that a UI is auto populating the content type but this is also a _real_ scenario which doesn't have a workaround at all (except me implementing an override for the Read method in the MediaTypeApiVersionReader and handling the accept header instead).

I also don't agree with not considering the accept header at all if the content-type is supplied because there are a few more complex scenarios which may add some complexity to the version selector. There is currently an implementation for getting the value out of the accept header (ReadAcceptHeader method) which doesn't consider the more complex scenarios so would it not be better to allow both content-type and accept headers to be checked with the currently implemented methods and drawing a line in the sand about version discrepancies by throwing an **AmbiguousApiVersionException** exception?  

I appreciate that the RESTful way would be to support all aspects, including the "I want to send v1 but receive v2" and appreciate that the current attribute structure in this framework doesn't really allow for this to be supported easily but ignoring the accept header completely seems more incorrect than not supporting all aspects of REST, especially when most of the text about how to handle versioning through content negotiation is through the accept header

**Comment by commonsensesoftware** [comment] 2017-06-29 18:08
We all have biases and preferences. As you've seen, there is definitely no shortage of them with respect to API versioning, including whether it's even necessary. I have my own opinions just like everyone else, but I try to limit them to help the broader community at large. I, for one, am not a fan of the API version in the URL segment at all. ;) You've obviously spent some amount of time looking at the code. Thanks. That makes the discussion a bit easier.

Let me try a simpler explanation:
* **Content-Type** = required; the server **must** understand
* **Accept** = optional; the server **may** understand/support the requested format

By [spec](http://www.ietf.org/rfc/rfc2616.txt), **Content-Type** is technically optional at the HTTP level, but that seemingly nonsensical for web platforms. The server is allowed to assume a media type by the resource URL, other information that might indicate the media type (say a file extension), or fallback to assume **application/octet-stream**. To my knowledge, this type of content negotiation is not supported by any flavor of ASP.NET. If it is supported, then I would say your position has more strength.

The primary usage for API versioning seems to be _controller per API version_, but the library supports other variations, including API version interleaving (e.g. multiple APIs on a single controller) and all API versions on a single controller (e.g. API version-neutral). It's possible to support _"I want to send v1, but receive v2"_, but I'm not sure this library would be helping much in that context. Furthermore, you'd have to write a bunch of code to handle this scenario in your controllers. This partially due to the way ASP.NET handles requests. Only a single controller can handle a request. Media type negotiation in ASP.NET is designed to be a cross-cutting concern; however, when using API versioning with a media type, it's not an independent concern anymore. The media type parameter has affinity to an API version and, hence, some controller. It isn't simple to split parts of the request that way.

Attributes aren't really the problem. It's more systemic. In fact, the libraries don't care about attributes for making decisions. It uses the **IApiVersionProvider** interface. A very common use case just so happens to be realized with attributes. You can also use conventions or your own custom mechanisms.

Hopefully, I haven't gone to tangential again. I want to help you solve your challenge, but I also want to better understand why you think it should be the default. As you've already mentioned, you can easily get the behavior you want with minimal investment by extending the existing **MediaTypeApiVersionReader**. It also appears that your challenge is specific to some UI dimension. I never quite understand why anyone would want API versioning for UIs, but I'm sure you have your reasons (you're not the first).

I can't say how many people have started using the media type versioning approach. It's definitely less than the other methods. Since it hasn't had as much usage, there are likely gaps. I'm not yet convinced this is one of them. It sounds like the only issue is getting the UI to postback with the correct media type, which includes the corresponding API version, no? If that can be accomplished, isn't that equally a viable solution? I would think that it should be as simple as:

```html
<form action="/home" method="post" enctype="multipart/form-data; v=1.0">
</form>
```

Thoughts?

**Comment by commonsensesoftware** [comment] 2017-07-10 21:51
I'm just curious if my suggestion worked for you or whether you came up with an alternate solution.

While I'm at it, let me try one more hashing of the HTTP header meanings as they are used:

* **Content-Type** : I (the client) am sending you (the server) something, including the API version
* **Accept** : You (the server) are sending me (the client) something I requested, including the API version

If I'm sending the server something, I have to specify **Content-Type** and that is logically the best place to include the API version too. If I'm only making a request without any content, **Accept** is logically the best place to include the API version. **Accept** still feels a bit awkward for `DELETE` since you don't provide input nor expect a response, but I've yet to find a better alternative.

The **MediaTypeApiVersionReader** is only meant to find one API version. Although the client can specify both the **Content-Type** and **Accept** headers, they usually only specify one or the other (but not always). I worry that changing the current behavior could be confusing. Furthermore, what does it mean when both headers are specified, but one of them does not contain the API version parameter? Is that supposed to be unspecified, ambiguous, ignored? If simply elaborating these behaviors further in the wiki will help, I'm happy to do so.

**Comment by commonsensesoftware** [comment] 2017-08-01 21:39
For the time being, I think this discussion has reached a conclusion. I certainly appreciate the conversation and debate as to what the _default_ behavior should be. For now, I'm not convinced there is much value in a change. I strongly believe that if content is provided by a client, then that is the only place where the API version should be derived from with respect to media type.

There are a couple of additional points for you or anyone else that may read this thread:
* Changing the **IApiVersionSelector** to the **LowestImplementedApiVersionSelector** or **CurrentImplementationApiVersionSelector** should allow matching the oldest or newest API version, when no API version is provided
  * This approach _could_ address your UI scenario where an API version isn't provided
* A new, custom **IApiVersionSelector** can be implemented with special matching rules based on the incoming request
* The provided **MediaTypeApiVersionReader** can be extended or a new **IApiVersionReader** can be implemented which adheres to the specific behaviors that you want (e.g. consider both headers)
* Version-neutral actions (ex: `DELETE`) could be split into separate version-neutral controllers
  * Since I don't currently have _by media type_ example yet, I may create one that demonstrates this exact scenario

**Closed by commonsensesoftware** 2017-08-01 21:39 UTC
Labels: answered, question
