### ISSUE TITLE
batch fails with versioning

### ISSUE THREAD

**Issue by Benjamin-Berry** [microsoft/aspnet-api-versioning#482] opened 2019-04-08 18:37 UTC
When adding versioning the batch processing is now broken. 

I can POST twice in a batch but if I PUT then next call comes back as ambiguous. Here the next call is a delete to a different controller.

The integration tests show all the calls work outside if a batch and the batch was working before adding the versioning.

-Update, I tried reordering the operations in the batch and the second one always fails.

I've sanitized the following for namespaces.

Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action 
DataSetsController.PutDataSet  in 1030.1843ms
Microsoft.AspNetCore.Routing.RouteBase:Debug: Request successfully matched the route with name 'odata-1.0' and template 'odata/v{version:apiVersion}/{*odataPath}'
Microsoft.AspNetCore.Mvc.Versioning.ODataApiVersionActionSelector:Debug: Action 'DataSetsController.GetDataSet (Service)' with id 'a1a3ad0f-bdf6-4192-94f9-df40b10bb8cd' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint'
Microsoft.AspNetCore.Mvc.Versioning.ODataApiVersionActionSelector:Debug: Action 'DataSetsController.PutDataSet (Service)' with id 'e97ee741-b6ad-4c5d-a9f9-eb380aef8ce9' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint'
Microsoft.AspNetCore.Mvc.Routing.DefaultApiVersionRoutePolicy:Error: Request matched multiple actions resulting in ambiguity. Matching actions: DataSetsController.PutDataSet(Guid, DataSet) (Service)
DataSetsController.DeleteDataSet(Guid) (Service)
Exception thrown: 'Microsoft.AspNetCore.Mvc.Internal.AmbiguousActionException' in Microsoft.AspNetCore.Mvc.Versioning.dll

[ApiVersion("1.0")]
  [ODataRoutePrefix("DataSets")]
  public class DataSetsController : ODataController

[ODataRoute("({key})")]
    [HttpPut]
    public async Task<IActionResult> PutDataSet([FromRoute]Guid key, [FromBody]DataSet dataSet)

[ApiVersion("1.0")]
  [ODataRoutePrefix("Figures")]
  public class FiguresController : ODataController

[ODataRoute("({key})")]
    [HttpDelete]
    public async Task<IActionResult> DeleteFigure([FromRoute]int key)

HTTP/1.1 100 Continue

POST /odata/v1/$batch HTTP/1.1
OData-Version: 4.0
OData-MaxVersion: 4.0
Content-Type: multipart/mixed; boundary=batch_6f7e1cb3-701e-45fe-bd22-25cc6a27c52a
Accept: multipart/mixed
Accept-Charset: UTF-8
User-Agent: Microsoft.OData.Client/7.5.4
Host: localhost:53223
Content-Length: 1522
Expect: 100-continue

--batch_6f7e1cb3-701e-45fe-bd22-25cc6a27c52a
Content-Type: multipart/mixed; boundary=changeset_51352a7a-1525-4d5d-ae99-ca9a88028f62

--changeset_51352a7a-1525-4d5d-ae99-ca9a88028f62
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

POST http://localhost:53223/odata/v1/DataSets HTTP/1.1
OData-Version: 4.0
OData-MaxVersion: 4.0
Content-Type: application/json;odata.metadata=minimal
Prefer: return=representation
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft.OData.Client/7.5.4

{"@odata.type":"#DataSet","DataSetId":"00000000-0000-0000-0000-000000000000","Name":"BatchMessage1"}
--changeset_51352a7a-1525-4d5d-ae99-ca9a88028f62
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 2

POST http://localhost:53223/odata/v1/DataSets HTTP/1.1
OData-Version: 4.0
OData-MaxVersion: 4.0
Content-Type: application/json;odata.metadata=minimal
Prefer: return=representation
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft.OData.Client/7.5.4

{"@odata.type":"#DataSet","DataSetId":"00000000-0000-0000-0000-000000000000","Name":"BatchMessage2"}
--changeset_51352a7a-1525-4d5d-ae99-ca9a88028f62--
--batch_6f7e1cb3-701e-45fe-bd22-25cc6a27c52a--
HTTP/1.1 200 OK
Date: Mon, 08 Apr 2019 17:41:19 GMT
Content-Type: multipart/mixed;boundary=batchresponse_12171aa3-9666-4577-91dc-f68896bd2c44
Server: Kestrel
Transfer-Encoding: chunked
OData-Version: 4.0

--batchresponse_12171aa3-9666-4577-91dc-f68896bd2c44
Content-Type: multipart/mixed; boundary=changesetresponse_664b8b8c-d44c-4759-8cb2-df95ef86c620

--changesetresponse_664b8b8c-d44c-4759-8cb2-df95ef86c620
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

HTTP/1.1 201 Created
Location: http://localhost:53223/odata/v1/DataSets(da212d0e-d64a-48bc-81e3-08d6bc49682e)
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
OData-Version: 4.0

{"@odata.context":"http://localhost:53223/odata/v1/$metadata#DataSets/$entity","DataSetId":"da212d0e-d64a-48bc-81e3-08d6bc49682e","Name":"BatchMessage1"}
--changesetresponse_664b8b8c-d44c-4759-8cb2-df95ef86c620
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 2

HTTP/1.1 201 Created
Location: http://localhost:53223/odata/v1/DataSets(b4e0d18d-c0a9-4004-81e4-08d6bc49682e)
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
OData-Version: 4.0

{"@odata.context":"http://localhost:53223/odata/v1/$metadata#DataSets/$entity","DataSetId":"b4e0d18d-c0a9-4004-81e4-08d6bc49682e","Name":"BatchMessage2"}
--changesetresponse_664b8b8c-d44c-4759-8cb2-df95ef86c620--
--batchresponse_12171aa3-9666-4577-91dc-f68896bd2c44--
HTTP/1.1 100 Continue

POST /odata/v1/$batch HTTP/1.1
OData-Version: 4.0
OData-MaxVersion: 4.0
Content-Type: multipart/mixed; boundary=batch_aea85057-5d29-4d55-b97a-d2c069022ad1
Accept: multipart/mixed
Accept-Charset: UTF-8
User-Agent: Microsoft.OData.Client/7.5.4
Host: localhost:53223
Content-Length: 1783
Expect: 100-continue

--batch_aea85057-5d29-4d55-b97a-d2c069022ad1
Content-Type: multipart/mixed; boundary=changeset_f63fe221-0b9f-47db-8951-b8c339535b0e

--changeset_f63fe221-0b9f-47db-8951-b8c339535b0e
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 2

PUT http://localhost:53223/odata/v1/DataSets(da212d0e-d64a-48bc-81e3-08d6bc49682e) HTTP/1.1
OData-Version: 4.0
OData-MaxVersion: 4.0
Content-Type: application/json;odata.metadata=minimal
Prefer: return=representation
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft.OData.Client/7.5.4

{"@odata.type":"#DataSet","DataSetId":"da212d0e-d64a-48bc-81e3-08d6bc49682e","Name":"BatchMessage1a"}
--changeset_f63fe221-0b9f-47db-8951-b8c339535b0e
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 3

POST http://localhost:53223/odata/v1/Figures HTTP/1.1
OData-Version: 4.0
OData-MaxVersion: 4.0
Content-Type: application/json;odata.metadata=minimal
Prefer: return=representation
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft.OData.Client/7.5.4

{"@odata.type":"#Figure","BackgroundColor":0,"DataSetId":"da212d0e-d64a-48bc-81e3-08d6bc49682e","FigureId":0,"FigureType":null,"ForegroundColor":0,"HideFigureAbove":0.0,"HideFigureAboveUnits":null,"HideLabelAbove":0.0,"HideLabelAboveUnits":null,"Style":null,"Width":0,"EmbeddedText":null,"Intervisibility":null,"Label":null}
--changeset_f63fe221-0b9f-47db-8951-b8c339535b0e--
--batch_aea85057-5d29-4d55-b97a-d2c069022ad1--
HTTP/1.1 200 OK
Date: Mon, 08 Apr 2019 17:41:22 GMT
Content-Type: multipart/mixed;boundary=batchresponse_64014c0d-af3c-4d75-a297-d3f78b8fab44
Server: Kestrel
Transfer-Encoding: chunked
OData-Version: 4.0

--batchresponse_64014c0d-af3c-4d75-a297-d3f78b8fab44
Content-Type: multipart/mixed; boundary=changesetresponse_b429a336-bc0e-429e-86e8-ef5fba82149a

--changesetresponse_b429a336-bc0e-429e-86e8-ef5fba82149a
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 3

HTTP/1.1 500 Internal Server Error

--changesetresponse_b429a336-bc0e-429e-86e8-ef5fba82149a--
--batchresponse_64014c0d-af3c-4d75-a297-d3f78b8fab44--

**Comment by Mhirji** [comment] 2019-05-01 08:31
After my moment of stupidity issue #493, I am now running into this as well.

**Comment by Mhirji** [comment] 2019-05-01 15:09
also came across this which seems to be related . . . 
https://github.com/OData/WebApi/issues/1754

**Comment by commonsensesoftware** [comment] 2019-05-01 15:27
I'm surprised they didn't just kick it back over here and close it out. This is a good find and will certainly help in the investigation/solution. Thanks.

**Comment by Mhirji** [comment] 2019-05-01 15:42
hopefully it makes up for my moment of stupidity !! :)

**Comment by commonsensesoftware** [comment] 2019-05-10 17:18
A quick update. This issue seems to be related to using the URL segment method. I was able to make things work just fine using the query string method. I'm not 100% sure the cause yet, but it appears to be the way OData routes are mapped to the batch handler. I haven't reached a conclusion yet, but it's looking like the solution is purely configuration. I'll report back once I know what the correct configuration is.

**Comment by commonsensesoftware** [comment] 2019-05-13 23:57
Scratch the tidbit about URL segment method; I goofed. I forgot that the route prefix did not include `api/` so the wrong URL was being requested.

**Comment by commonsensesoftware** [comment] 2019-05-14 00:09
This does look like it's related to the issue that @Mhirji cited.  Fortunately, I have a workaround for this. It's not really documented anywhere because you're not _supposed_ to have to ever do this. I would argue that there is a bug in the OData code that generates a new **HttpContext** without copying over _features_.

To work around this problem, you need to manually control the order of middleware because the order is critically important in this scenario.

### Step 1
Disable auto-registration of the API Versioning middleware. This currently doesn't do anything, but add the **IApiVersioningFeature**.

Change your setup as follows:

```c#
services.AddApiVersioning(options => options.RegisterMiddleware = false);
```

### Step 2
Register the API Versioning middleware **after** the OData batching middleware.

Change your setup to:

```c#
public void Configure( IApplicationBuilder app, VersionedODataModelBuilder modelBuilder )
{
    app.UseODataBatching();
    app.UseApiVersioning();
    app.UseMvc(
        routeBuilder =>
        {
            var models = modelBuilder.GetEdmModels();
            Func<ODataBatchHandler> batchHandlerFactory = () => new DefaultODataBatchHandler();
            routeBuilder.MapVersionedODataRoutes( "odata", "api", models, batchHandlerFactory );
        } );
}
```

### Step 3
Run your app and enjoy!

------

API Versioning auto-wires itself up, which ends up registering its middleware before OData. Due to the implementation in OData, when you enable batching, it needs to occur **after** the batching middleware is registered. I wouldn't call this is a bug on the API Versioning side, but it definitely isn't obvious this is what you need to do in order to set things up.

I'll see what the OData team does. If they provide a fix for copying features, then all will be good in the world; otherwise, I'll add something to the wiki that describes this particular setup. Manually configuring the middleware is vaguely discussed, but not in this context. It's not something you are _supposed_ to have to worry about.

**Comment by commonsensesoftware** [comment] 2019-06-28 15:18
After some more research, it would appear there is no _magic_ way that OData could properly copy or recreate features for each subsequent request. That means the solution I've provided is the setup you should always use for this scenario. I'm consider/investigate improving the setup in the future.

Are there any more questions on this issue or has it been resolved? It seems to be resolved.

**Comment by commonsensesoftware** [comment] 2019-07-01 15:47
I believe this issue has now been resolved. I've added this documentation to the wiki [here](../wiki/OData-Batching) so that it will easily discoverable in the future. Feel free to come back or reopen the issue if you continue to have trouble. Thanks.

**Closed by commonsensesoftware** 2019-07-01 15:47 UTC
Labels: answered, asp.net core, odata

**Comment by Benjamin-Berry** [comment] 2019-07-16 14:03
Had time to get back to this. Confirmed the work around works.

**Comment by jtTorres** [comment] 2021-01-18 19:58
I pulled the sample aspne-api-versioning and tried adding $batch to the ODataBasicSample project and it did not work.
I followed the instructions in the wiki but still nothing.  It seems like it's trying to obtain the IApiVersioningFeature but that's returning a null so it's not able to access anything else.

**Here's my setup:**
```csharp
public void ConfigureServices( IServiceCollection services )
        {
            services.AddControllers();
            services.AddApiVersioning(
                options =>
                {
                    options.ReportApiVersions = true;
                    options.RegisterMiddleware = false;
                } );
            services.AddOData().EnableApiVersioning();
        }

public void Configure( IApplicationBuilder app, VersionedODataModelBuilder modelBuilder )
        {
            app.UseODataBatching();
            app.UseApiVersioning();
            app.UseRouting();
            app.UseEndpoints(
                endpoints =>
                {
                    var models = modelBuilder.GetEdmModels( "api" );
                    var batchHandler = new DefaultODataBatchHandler();
                    endpoints.MapControllers();
                    endpoints.MapVersionedODataRoute( "odata", "api", models, batchHandler );
                } );
        }

 ```

**Here's the error message I get:**
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.AspNetCore.Mvc.Versioning
  StackTrace:
   at Microsoft.AspNetCore.Mvc.Routing.ApiVersionUrlHelper.get_RouteParameter() in ...\Microsoft.AspNetCore.Mvc.Versioning\Routing\ApiVersionUrlHelper.cs:line 37

![image](https://user-images.githubusercontent.com/34681040/104958194-2fb01480-5995-11eb-8f1a-19cee4616a90.png)
