### ISSUE TITLE
System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance. Microsoft.AspNet.WebApi.Versioning

### ISSUE THREAD

**Issue by abdkayali** [microsoft/aspnet-api-versioning#705] opened 2020-12-03 09:51 UTC
I'm working on an OData Solution based on ASP.NET, and I came to the point to add nuget packages for api versioning, so I ended up adding the following:

`Microsoft.AspNet.OData.Versioning` v5.0.0
`Microsoft.AspNet.WebApi.Versioning` v4.1.0

Upon building and testing the code, I get the following exception for whatever request:

`Exception Details: System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance.`

Stack Trace:
```
[InvalidOperationException: ValueFactory attempted to access the Value property of this instance.]
   System.Lazy`1.CreateValue() +429
   System.Lazy`1.LazyInitValue() +158
   System.Lazy`1.get_Value() +79
   Microsoft.Web.Http.Dispatcher.ApiVersionControllerSelector.GetControllerMapping() in /_/src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/ApiVersionControllerSelector.cs:49
   System.Web.Http.Routing.AttributeRoutingMapper.AddRouteEntries(SubRouteCollection collector, HttpConfiguration configuration, IInlineConstraintResolver constraintResolver, IDirectRouteProvider directRouteProvider) +48
   System.Web.Http.Routing.<>c__DisplayClass1_1.<MapAttributeRoutes>b__1() +57
   System.Web.Http.Routing.RouteCollectionRoute.EnsureInitialized(Func`1 initializer) +61
   System.Web.Http.Routing.<>c__DisplayClass1_0.<MapAttributeRoutes>b__0(HttpConfiguration config) +91
   System.Web.Http.HttpConfiguration.ApplyControllerSettings(HttpControllerSettings settings, HttpConfiguration configuration) +70
   System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type) +165
   System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type) +54
   System.Web.Http.Controllers.HttpControllerDescriptor..ctor(HttpConfiguration configuration, String controllerName, Type controllerType) +105
   Microsoft.Web.Http.Dispatcher.ApiVersionControllerSelector.InitializeControllerInfoCache() in /_/src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/ApiVersionControllerSelector.cs:171
   System.Lazy`1.CreateValue() +429
   System.Lazy`1.LazyInitValue() +158
   System.Lazy`1.get_Value() +79
   Microsoft.Web.Http.Dispatcher.ApiVersionControllerSelector.GetControllerMapping() in /_/src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/ApiVersionControllerSelector.cs:49
   Microsoft.AspNet.OData.Builder.VersionedODataModelBuilder.GetApiVersions() in /_/src/Microsoft.AspNet.OData.Versioning/AspNet.OData/Builder/VersionedODataModelBuilder.cs:46
   Microsoft.AspNet.OData.Builder.VersionedODataModelBuilder.GetEdmModels(String routePrefix) in /_/src/Common.OData/AspNet.OData/Builder/VersionedODataModelBuilder.cs:62
   Microsoft.AspNet.OData.Builder.VersionedODataModelBuilder.GetEdmModels() in /_/src/Common.OData/AspNet.OData/Builder/VersionedODataModelBuilder.cs:53
   Web.WebApiConfig.Register(HttpConfiguration config) in <Solution_Path>\Web\App_Start\WebApiConfig.cs:39
   System.Web.Http.GlobalConfiguration.Configure(Action`1 configurationCallback) +34
   Web.WebApiApplication.Application_Start() in <Solution_Path>\Web\Global.asax.cs:13

[HttpException (0x80004005): ValueFactory attempted to access the Value property of this instance.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +475
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +176
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +220
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +303

[HttpException (0x80004005): ValueFactory attempted to access the Value property of this instance.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +659
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +89
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +188
```

I managed to fix the problem on my solution by downloading the source code from [microsoft/aspnet-api-versioning](https://github.com/microsoft/aspnet-api-versioning) then adding reference to projects: Microsoft.AspNet.OData.Versioning, Microsoft.AspNet.WebApi.Versioning and apply the change described below:

File: `Microsoft.AspNet.WebApi.Versioning\Dispatcher\ApiVersionControllerSelector.cs` Line: 39
`controllerInfoCache = new Lazy<ConcurrentDictionary<string, HttpControllerDescriptorGroup>>( InitializeControllerInfoCache, System.Threading.LazyThreadSafetyMode.PublicationOnly );`

I added the second parameter of the constructor, and exception is gone. But still I wish to have this fixed in the nuget package so I don't need to keep the reference to the project all the time.

Thanks,

**Comment by commonsensesoftware** [comment] 2021-04-01 06:30
Apologies for the delayed response. I started looking into this again. Thanks for the repo. It helped.

In the repo, `CustomizedEnableQueryAttribute` is incorrect (maps the wrong property), but swapping it with good old `EnableQueryAttribute` works just fine.

The issue appears to be that in `WebApiConfig.Regsiter` you have:

```c#
httpConfig.MapHttpAttributeRoutes();
```

You should **not** do that. In the old Web API stack, mixing attribute and convention-based routing doesn't always work with API Versioning. OData only supports convention-based routing (despite it's use of attributes; it's completely different). This is called out in the [wiki](../wiki/Known-Limitations#odata-routing) and in the [Advanced OData Sample](../blob/master/samples/webapi/AdvancedODataWebApiSample/Startup.cs#L50).

There's a chance that this is some kind of regression. I would have missed it because no tests or examples mix the routing styles. I've tried several times and I cannot make it work properly in all cases on the old stack when you mix things. If you're going to mix vanilla and OData controllers, the recommendation is to **only** use convention-based routing.

Things should not fail this way, so I'll continue looking at it to see if there's a better solution. Honestly, it's a bit lower on the priority list because there are workarounds, but I don't want to completely ignore it. I'm not convinced that simply changing the `Lazy<T>` initialization is the _right_ solution. That simply allows things to be called multiple times, keeping one.

To further illustrate the wonkiness, if you move `httpConfig.MapHttpAttributeRoutes()` after all other calls to `httpConfig.MapVersionedODataRoute`, things will work as well. That type of ordering is brittle and should not be necessary, but it's one more limitation in the way the old routing system works. I don't recommend that as a solution, but it _might_ work and be acceptable for you.

**Comment by commonsensesoftware** [comment] 2021-06-15 16:32
Having stared at this many times, I don't think there is a better solution on the old stack. Some closing thoughts:

- Do **not** mix routing styles; it only leads to hard-to-troubleshoot issues
- This also means do **not** call `HttpConfiguration.MapHttpRouteAttributes()`
- Do **not** explicitly invoke `HttpConfiguration.Initialize`; this can lead to recursion

Changing the behavior of the `Lazy<T>` initialization _fixes_ the issue by simply ignoring it, but I don't think that's the right long-term solution. This is the exact same initialization used by the original Web API code. When this error occurs, it tells you that recursion has occurred when it shouldn't have. While the error isn't very unhelpful, it does indicate a misconfiguration. Hiding that may lead to additional issues.

Hopefully this guidance led you to a long-term solution. If not, free feel to reopen or post a new issue for further discussion.

**Closed by commonsensesoftware** 2021-06-15 16:32 UTC
Labels: asp.net web api, odata
