### ISSUE TITLE
ApiExplorer ApiDescription error: The invoked member is not supported before the type is created.

### ISSUE THREAD

**Issue by dmore234** [microsoft/aspnet-api-versioning#463] opened 2019-02-23 04:25 UTC
Using WebApi and oData v4. Getting exception in MultipleVersion block for EF models having navigation property. Do I have add IncludeNavigationPropery in Swagger Config file or exclude controllers having navigation property? Please advise!

The invoked member is not supported before the type is created.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NotSupportedException: The invoked member is not supported before the type is created.

 foreach (var group in apiExplorer.ApiDescriptions)....................Line 152:

**Comment by commonsensesoftware** [comment] 2019-02-23 17:34
Which version of the libraries are you using? Are you using the current versions? There was an issue related to this area that has since been fixed, but there still might be a missing edge case.

Do you have a simple repro or configuration you can share. It's difficult to setup the conditions you're seeing otherwise. Thanks.

**Comment by dmore234** [comment] 2019-02-25 13:57
Swashbuckle oData 3.5.0. Rest latest version.

**Comment by dmore234** [comment] 2019-02-25 15:43
I have multiple oData controllers, is there a way to hide/not display certain controllers in Swagger UI? 

I tried class level attribute [ApiExplorerSettings(IgnoreApi=true)] but it not working.

Thanks for your help!

**Comment by commonsensesoftware** [comment] 2019-02-25 17:09
Oh … I _think_ I see. Are you using the [Swashbuckle.OData](https://github.com/rbeauchamp/Swashbuckle.OData)? If so, that's the culprit. It changes things that break API versioning. Fear not though. There's a solution and you don't need that package at all.

I **strong** recommend you have a deep look at the [Web API OData Swagger](../tree/master/samples/webapi/SwaggerODataWebApiSample) sample project. It will show you all the packages and setup you need to get OData and Swagger working together.

API Versioning provides an extension to the _API Explorer_ API. One of its possible uses for Swagger generation. As a result, you don't need a special variant of Swashbuckle or other Swagger generators like NSwag that use this information. You need API Versioning and plain 'ol Swashbuckle.

In your case, you packages should include:
* API Versioning for OData on Web API
* API Versioning API Explorer for OData on Web API
* Swashbuckle

Again - the working example will demonstrate everything work end-to-end. Give that a whirl and let me know if you have more questions.

I may need to put something on the wiki as the incompatibility with **Swashbuckle.OData** has come up a few times.

**Comment by dmore234** [comment] 2019-02-25 18:17
In mentioned sample project ( .../aspnet-api-versioning-master\samples\webapi\SwaggerODataWebApiSample\Models) model Order & Person does NOT have Navigation Property.

ApiVersioning is working w/o Navigation property. I am getting error w NP.

**Comment by commonsensesoftware** [comment] 2019-02-26 16:20
Navigation properties should be supported. I'll investigate further. If you have a repro or an example to share that really helps speed things up so that I can run through your _exact_ scenario.

**Comment by dmore234** [comment] 2019-02-26 16:43
I used the sample code from sample you mentioned in recent past
( .../aspnet-api-versioning-master\samples\webapi\SwaggerODataWebApiSample\Models) model Order & Person


In this sample project can you add NP in Order / Person and see if multiple versioning is working or not.

Steps are:
1) Use models with NP
2) Add [Apiversion("1.0")] and 2.0 in two controllers
3) Use c.MultipleVersion code in Startup.cs ....v{apiversion}

Expectation is there should be 2 v1 & v2 in dropdown. All odata query should work like $select, $top $ expand....

Hope this will help!

Thanks!

Dilip More






Thanks for our help!

Dilip More



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by commonsensesoftware** [comment] 2019-02-26 16:47
Great, that's easier to start from; however, that the sample doesn't have any navigation properties. So what did you add or change?

**Comment by dmore234** [comment] 2019-02-26 16:50
In our code ( model ) we had a NP in few models as this code is used for oData query. I just added the c.Multipleversion code.
in our project code



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by commonsensesoftware** [comment] 2019-03-05 17:34
I'm not sure how old your sync of the repo is. I've been unable to reproduce the specific error you're describing. I added a _Line Items_ navigation property to the _Orders_ entity set and things worked as expected. I even varied the model between API versions, which would would trigger _model substitution_. Are you sure you have the most recent updates in the repo? There was a problem that has since been fixed for a while now.

As an aside, I am noticing an issue with navigation properties that are defined by _convention_. I'm not sure if it's a bug yet or just my misconfiguration. Personally, I prefer the attribute route approach, but both methods are _supposed_ to work. I'll continue investigating.

**Comment by dmore234** [comment] 2019-03-06 03:38
Can you please share the sample code where odata controller api versioning is working  with navigation property entity?

**Comment by commonsensesoftware** [comment] 2019-03-06 23:10
It's incomplete, but I pushed my [working branch](../tree/dev/chrimart/odata-fixes-201903/samples/webapi/SwaggerODataWebApiSample) for you to look at. This updated example for Web API adds navigation properties using attribute and convention-based routing. Both routing methods resolve correctly, but the Swagger documentation isn't showing up for convention-based navigation properties. This is probably a bug in the API Explorer, but I'm still investigating.

Hopefully, this will be useful to you.

**Comment by commonsensesoftware** [comment] 2019-04-30 17:11
Apologies for the long delay. Finally back to digging into this more. There is definitely a bug with navigation properties by convention; they simply are not generated. I have a basic fix for that; however, there may be additional issues with generating other types of complex navigation properties by convention such as for links (e.g. `$ref`).

Against what I'd _like_, I'm inclined to get the basic functionality out and revisit the more complex scenarios later in a separate issue. I believe the main issues stem from convention-based routes since attribute-based routes explicitly say what the template is supposed to be. Generating the correct route templates purely from reflecting the code is non-trivial. I do believe covering all of the OData conventions is ultimately possible, but the value proposition of waiting until I can iron out all possibilities seems low when the most common scenarios can be address now.

There's quite a few issues under investigation right now. I plan on addressing as many as I can before the next release to avoid churn. Thanks for you patience.

**Comment by commonsensesoftware** [comment] 2019-05-01 16:14
This issue will be resolved after the next package push. Supporting all conventions will be addressed in a future iteration that is now tracked by #494. Thanks.

**Closed** 2019-07-01 21:06 UTC
Labels: asp.net web api, bug, odata
