### ISSUE TITLE
UnsupportedApiVersion when methods follow different pattern

### ISSUE THREAD

**Issue by Sangoria** [Microsoft/aspnet-api-versioning#288] opened 2018-05-02 13:15 UTC
Couldn't find other issues reproducing what seems to be a bug:

```C#
[ApiVersion("1.0")]
[ApiVersion("2.0")]
[ApiVersion("3.0")]
[RoutePrefix("api/v{version:apiVersion}/values")]
public class ValuesController : ApiController
{
    [MapToApiVersion("1.0")]
    [Route("")]
    [HttpGet]
    public string EventsV1([FromUri] string username = "", [FromUri] string serialNumber = "")
    {
        return "testv1";
    }

    [MapToApiVersion("2.0")]
    [Route("")]
    [HttpGet]
    public string EventsV2([FromUri] string username = "", [FromUri] string serialNumber = "")
    {
        return "testv2";
    }

    [MapToApiVersion("3.0")]
    [Route("")]
    [HttpGet]
    public string Test([FromUri] string username, [FromUri] string serialNumber)
    {
        return "testv3";
    }
}
```

With this current code, trying to hit `/api/v1/values?username=test&serialNumber=test` results in the following error:

> The requested resource with API version '1' does not support HTTP method 'GET'.

However trying to hit `/api/v3/values?username=test&serialNumber=test` works fine.

Now if I change the signature of the `Test` method to match all other signatures, it seems to work fine in all scenarios:

```C#
 public string Test([FromUri] string username = "", [FromUri] string serialNumber = "")
```

So it seems that there is some sort of edge case issue going on here.

**Comment by commonsensesoftware** [comment] 2018-05-02 15:52
I'm afraid this appears to be a behavior of how routing works in Web API. The routing infrastructure considers values bound to the **IModelBinder** for `[FromUri]` to be required **unless** they have a default value. The default values themselves do not need to be the same, but a default value is nonetheless required.

API versioning doesn't change the fundamentals of routing. After you boil everything away, what you're left with is simple logic that just disambiguates otherwise ambiguous routes using an API version value.

To meet your specific needs, I would consider:

* Use a custom **IModelBinder** instead of `[FromUri]`
  * You might even able to extend it
* Make the action with the required parameters default to `null` and then perform the validation in the action (e.g. return 404 or 400)
   * This could arguably be done with an action filter too

I hope that help.s

**Comment by commonsensesoftware** [comment] 2018-05-02 16:34
What was the request URL? I tried your setup and I cannot reproduce success. I removed API versioning, but Web API still reports the following error response for `http://localhost/api/v3/values`:

```json
{
 "Message": "No HTTP resource was found that matches the request URI 'http://localhost/api/v3/values'.",
 "MessageDetail": "No action was found on the controller 'Values' that matches the request."
}
```

If I include the query parameters, then things work as expected. Am I missing something or is there something else different about your setup?

**Comment by Sangoria** [comment] 2018-05-02 16:40
Request URLs are:

- `http://localhost/api/v1/values?username=test&serialNumber=test`
- `http://localhost/api/v2/values?username=test&serialNumber=test`
- `http://localhost/api/v3/values?username=test&serialNumber=test`

Are you saying that my original question is working for you with these 3 URLs?

**Comment by commonsensesoftware** [comment] 2018-05-02 16:41
Yes - as long as the query parameters are provided. If the query parameters not provided, then `v3` fails with and without API versioning.

**Comment by Sangoria** [comment] 2018-05-02 16:59
I'm guessing this must be something else in in my setup then... I'll give you the relevant config in case something jumps up to you, otherwise I assume I'll have to figure out what is interfering.

This is my `WebApiConfig.cs`:

```C#
public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            var constraintResolver = new DefaultInlineConstraintResolver
            {
                ConstraintMap =
                {
                    ["apiVersion"] = typeof( ApiVersionRouteConstraint )
                }
            };

            config.MapHttpAttributeRoutes(constraintResolver);
            config.AddApiVersioning();

            // format the version as "'v'major[.minor][-status]"
            var apiExplorer = config.AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'VVV");

            config.EnableSwagger(
                    "{apiVersion}/swagger",
                    swagger =>
                    {
                        swagger.MultipleApiVersions(
                            (apiDescription, version) => apiDescription.GetGroupName() == version,
                            info =>
                            {
                                foreach (var group in apiExplorer.ApiDescriptions)
                                {
                                    info.Version(group.Name, $"API {group.ApiVersion}");
                                }
                            });
                    })
                .EnableSwaggerUi(swagger =>
                {
                    swagger.EnableDiscoveryUrlSelector();
                    swagger.DocumentTitle("API Name");
                    swagger.DisableValidator();
                });

            // Return JSON in camelCase instead of PascalCase
            config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            config.Formatters.JsonFormatter.UseDataContractJsonSerializer = false;
        }
    }
```

And `Application_Start()`:

```C#
protected void Application_Start()
        {
            // build the container and set the static service locator
            var container = ContainerUtil.BuildAndSetContainer(new ApiModule());

            //Set the WebApi DependencyResolver to Autofac
            GlobalConfiguration.Configuration.DependencyResolver = new AutofacWebApiDependencyResolver(container);

            GlobalConfiguration.Configure(WebApiConfig.Register);
            
            // log application start event
            var logger = container.Resolve<LoggerService.Factory>()(GetType().FullName);
            logger.Info($"Application Start Event. UTC Time - {DateTime.UtcNow}. Process Id is {GetProcessId()}");

            // start startables
            container.StartStartables();
        }
```

**Comment by commonsensesoftware** [comment] 2018-06-06 20:43
Sorry for the delayed response. In reviewing this again, I'm still convinced that you hit a snag related to how routes are mapped to action methods in Web API. I was able to repro your conditions with and without API versioning. I'm assuming you've found a solution or other workaround by now, but I thought I'd provide a quick follow-up before closing out this issue. Thanks.

**Comment by commonsensesoftware** [comment] 2018-06-13 15:48
It seems that you found a solution or otherwise resolved your issue. If not, feel free to re-open this issue or post a new one. Thanks

**Closed by commonsensesoftware** 2018-06-13 15:48 UTC
Labels: ASP.NET Web API, answered, question
